version = 0.1

[default.deploy.parameters]
stack_name = "career-coach-stack"
resolve_s3 = true
s3_prefix = "career-coach-stack"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []

[default.global.parameters]
region = "ap-southeast-1"
